apiVersion: v1
kind: Namespace
metadata:
  name: fgdfgdgf-dev
  labels:
    environment-id: env_9c92c82b-75e6-48b5-9925-576884f8e7db
    project-id: project_f987a4d7-17bb-46e8-8128-48a37ce1a4d8
    project-name: fgdfgdgf
    environment-name: dev
    organization-id: org_99bfadb5-996a-47d5-a5fc-442c14a28627
